### ISSUE TITLE
emojis are partially broken

### ISSUE THREAD

**Issue by onurmercury** [erynith/movie-web-instances#17]
on chromium/webview browsers:

![Screenshot_20240715-003313](https://github.com/user-attachments/assets/61b7bb3b-5f60-4376-8bdf-bcb66de19ebd)
![Screenshot_20240715-003349_Brave](https://github.com/user-attachments/assets/a23ee849-79a0-4b91-b4dc-f6015620f7bb)
![Screenshot_20240715-003405_Chrome](https://github.com/user-attachments/assets/7938ee86-5ff1-4bd1-a821-5d69902d7e46)

on firefox:

![Screenshot_20240715-003328](https://github.com/user-attachments/assets/88a158c5-252b-4332-868b-f6a02ed3f0a3)

**Comment by erynith** [comment]
please wait for the twemoji library to update their image links as the host maxcdn has shutdown

**Comment by erynith** [comment]
I have updated twemoji 👍
