### ISSUE TITLE
latest update to vidbinge adds sketchy ass subscription service.

### ISSUE THREAD

**Issue by miniozoid3** [erynith/movie-web-instances#19]
![firefox_5WQ5SEqxR0](https://github.com/user-attachments/assets/8351af4f-a21a-49ce-8c39-4f18cb98c779)
![JXGzeaSwHT](https://github.com/user-attachments/assets/542fb639-b0c6-4db3-b126-e99760eae76c)

**Comment by erynith** [comment]
I agree that it's sketchy but since there's a way to close it (and it doesn't open every few minutes/seconds) it should technically be all good

**Comment by erynith** [comment]
resolved
