### ISSUE TITLE
The vidbinge.com instance has redirect ads

### ISSUE THREAD

**Issue by smart-bee-hub** [erynith/movie-web-instances#20]
The "vid binge" instance of movie-web has harmful/scam redirect ads on desktop devices and desktop mode on mobile devices

**Comment by erynith** [comment]
when do you see them because I don't even see them with my ad blocker off idk

**Comment by smart-bee-hub** [comment]
It's a single redirect ad that covers the whole screen invisibly/the search
bad invisibly only in desktop mode, I got one using desktop mode on my
phone, in my pc and my xbox

**Comment by ztpn** [comment]
![KZP150E](https://github.com/user-attachments/assets/2e8d4531-ba36-40fc-ba57-60db9d18a755)

**Comment by erynith** [comment]
> ![KZP150E](https://private-user-images.githubusercontent.com/96815580/355155914-2e8d4531-ba36-40fc-ba57-60db9d18a755.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MDQ3MDQsIm5iZiI6MTcyMjkwNDQwNCwicGF0aCI6Ii85NjgxNTU4MC8zNTUxNTU5MTQtMmU4ZDQ1MzEtYmEzNi00MGZjLWJhNTctNjBkYjlkMThhNzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAwMzMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5YzI5NmZkN2QzY2U1ZjUyYTAzZWU1MTM3NDg1NTI5NmI1MTQ0NzE5ZTRkZjRiZTAxNTRjMTU4MGFjOGM0ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hd11h_1-oBBPW2nRdzxhgIaXxnnVaOSKqOhVLpOLSA0)

epic
