### ISSUE TITLE
mwa is gone

### ISSUE THREAD

**Issue by ibrahimmudassar** [erynith/movie-web-instances#7]
make this a place for alternative instances as well as github forks of the original

**Comment by erynith** [comment]
> make this a place for alternative instances as well as github forks of the original

but it is alternative instances bruh

**Comment by ibrahimmudassar** [comment]
I know, but what about hosting the code, or leading to other repos that have the code. I'm sure the instances will go down in time and the code will not work so I'm looking for a repo that continues the legacy

**Comment by erynith** [comment]
I dont think any open sourced repo will continue the legacy

**Comment by erynith** [comment]
> I know, but what about hosting the code, or leading to other repos that have the code. I'm sure the instances will go down in time and the code will not work so I'm looking for a repo that continues the legacy

u can check the page tho for saved repos
